---
title: "Untitled"
output: html_document
date: "2024-11-26"
---

```{r}
library(readr)
library(dplyr)
library(GUniFrac)
library(vegan)
library(ape)
library(ggrepel)
library(ggdendro)
library(gridExtra)
library(pheatmap)


zmap97 <- read_delim("zmap97.txt", delim = ";", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
zmap97_tidy <- read_csv("zmap97_tidy.txt", col_names = FALSE)
```


```{r}
zmap97$sample <- zmap97_tidy$X1

zmap97$X1 <- gsub("^.*le=","",zmap97$X1)

zmap97$X2 <- gsub("size=","",zmap97$X2)

colnames(zmap97) = c("SampleReadID","counts","ZOTU","Sample")

zmap97$counts <- as.numeric(zmap97$counts)

zmap97 %>% group_by(Sample, ZOTU) %>% summarise(zotu_counts = sum(counts))

```


```{r}
rare_rawreads <- reshape2::dcast(zmap97[,-c(1)], 
                                 Sample ~ ZOTU, 
                                 value.var = "counts", 
                                 fun.aggregate = sum)

rownames(rare_rawreads) <- rare_rawreads$Sample
rare_rawreads <- rare_rawreads[,-1]



pdf(file = "rarecurve.pdf", width = 4, height = 8)
rarecurve(rare_rawreads, step = 20,
          sample = 10000,
          col = "blue",
          cex = 0.6,
          main = "rarecurve()")
dev.off()
 
# filter out "A3" "A9" "D6" "S3" "S6" "S9" sampling sites
# normalize to 8000
rare_rawreads_norm <- as.data.frame(GUniFrac::Rarefy(rare_rawreads, depth = 8000)$otu.tab.rff)



write.csv(rare_rawreads, file = "sample_zotu_matrix_raw.csv", row.names = TRUE, col.names = TRUE, quote = FALSE)
write.csv(rare_rawreads_norm, file = "sample_zotu_matrix_norm.csv", row.names = TRUE, col.names = TRUE, quote = FALSE)
```




# alpha

```{r}
# 计算物种丰富度（ZOTU 数量）
richness <- specnumber(rare_rawreads_norm)

shannon <- diversity(rare_rawreads_norm, index = "shannon")

simpson <- diversity(rare_rawreads_norm, index = "simpson")

alpha_diversity <- data.frame(
  SamplingSite = rownames(rare_rawreads_norm),
  Richness = richness,
  Shannon = shannon,
  Simpson = simpson
)




# Reshape data to long format
alpha_div_long <- melt(alpha_diversity, id.vars = "SamplingSite", 
                       measure.vars = c("Richness", "Shannon"), 
                       variable.name = "Metric", value.name = "Value")

# Plot using facets
pdf(file = "/home/jordan/projects/Chiro/01.ZOTU_Results/AlphaDiversity_barplot.pdf", width = 10, height = 6)

ggplot(alpha_div_long, aes(x = SamplingSite, y = Value, fill = Metric)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~Metric, scales = "free_y") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"  # Remove legends
  ) +
  labs(title = "Alpha Diversity Metrics per Sampling Site",
       x = "Sampling Site",
       y = "Value")
dev.off()
```

# beta
```{r}
# 使用 Bray-Curtis 距离
distance_matrix <- vegdist(rare_rawreads_norm, method = "bray")

pcoa <- pcoa(distance_matrix)

# 提取坐标
pcoa_points <- as.data.frame(pcoa$vectors[,1:2])
pcoa_points$SamplingSite <- rownames(pcoa_points)

# 绘制 PCoA 图
pdf(file = "/home/jordan/projects/Chiro/01.ZOTU_Results/PCoA.pdf", width = 6, height = 6)

ggplot(pcoa_points, aes(x = Axis.1, y = Axis.2)) +
  geom_point(size = 3) +
  theme_minimal() +
  geom_text_repel(aes(label = SamplingSite), size = 3, max.overlaps = 5) +
  labs(title = "PCoA Plot Based on Bray-Curtis Distance",
       x = paste0("PCoA1 (", round(pcoa$values$Relative_eig[1]*100, 2), "%)"),
       y = paste0("PCoA2 (", round(pcoa$values$Relative_eig[2]*100, 2), "%)")) +
  theme(legend.position = "right")
dev.off()
```

```{r}
# 选择丰度最高的前 20 个 ZOTU
top_zotus <- names(sort(colSums(rare_rawreads_norm), decreasing = TRUE))[1:10]
otu_top <- rare_rawreads_norm[, top_zotus]


pdf("/home/jordan/projects/Chiro/01.ZOTU_Results/heatmap_top10ZOTU.pdf", width = 10, height = 6)
pheatmap(otu_top,
         scale = "row",
         clustering_distance_rows = "euclidean",
         clustering_distance_cols = "euclidean",
         clustering_method = "ward.D2",
         color = rev(colorRampPalette(c("red", "white", "green"))(10)),
         angle_col = 45,
         show_colnames = TRUE,
         show_rownames = TRUE)
dev.off()
```



```{r}
otu_melt <- melt(as.matrix(otu_top))
colnames(otu_melt) <- c("SamplingSite", "ZOTU", "Abundance")


otu_top_rel_matrix <- as.matrix(otu_top)
distance_matrix <- vegdist(otu_top_rel_matrix, method = "bray")
cluster <- hclust(distance_matrix, method = "ward.D2")  
ordered_sites <- cluster$labels[cluster$order]
otu_melt$SamplingSite <- factor(otu_melt$SamplingSite, levels = ordered_sites)


## dendrogram
dendro_data <- dendro_data(cluster)
dendro_plot <- ggplot() +
  geom_segment(
    data = dendro_data$segments,
    aes(x = x, y = y, xend = xend, yend = yend)
  ) +
  scale_x_continuous(
    breaks = dendro_data$labels$x,
    labels = dendro_data$labels$label
  ) +
  scale_y_reverse(expand = c(0, 0)) +   # Remove expansion to minimize spacing
  theme_void() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.margin = unit(c(1, 0, 1, 0), "lines"))


### barplot
barplot <- ggplot(otu_melt, aes(x = SamplingSite, y = Abundance, fill = ZOTU)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  theme(
    legend.position = "right",
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5),
    plot.margin = unit(c(1, 0, 1, 0), "lines")) +
  labs(
    title = "Relative Abundance of Top 10 ZOTUs in Sampling Sites (cluster sampling sites)",
    y = "Relative Abundance"
  )




pdf(file = "/home/jordan/projects/Chiro/01.ZOTU_Results/Relative_Abundance_barplot.pdf", width = 10, height = 6)
  barplot
dev.off()

pdf(file = "/home/jordan/projects/Chiro/01.ZOTU_Results/Relative_Abundance_dendro.pdf", width = 10, height = 6)
  dendro_plot
dev.off()


```

